### ISSUE TITLE
Need dark theme for this amazing outline

### ISSUE THREAD

**Issue by cloudnix** [warmdev/SublimeOutline#1]
Thanks a lot warmdev for your effort :+1: 

Please add dark theme or it can parrent with editor theme.

Thanks :+1:  :smiley:

**Comment by warmdev** [comment]
Glad you find this package useful. You can change the color theme with the following steps:

* Create a new copy of the `outline.hidden-tmTheme` file to override the original copy. This can be done in two ways:
    - Click `Preferences` and then `Browse Packages`, this opens the user packages folder. Create a new folder named `Outline`. Put this file https://raw.githubusercontent.com/warmdev/SublimeOutline/master/outline.hidden-tmTheme inside the `Outline` folder
    - Or, install the `PackageREsourceViewer` package via Package Contorl. Press `ctrl + shift + p` and select `PackageResourceViewer: Open Resource`. Find `Outline`, press Enter, and select `outline.hidden-tmTheme`. Press Enter again to open this file, and press ESC to close the `PackageResourceViewer` window. A copy of the opened file will be automatically saved in the user packages folder.
* Change the following color values (you can specify other color values as desired)
    - Change the HEX color in line 13 to `#272822` (This is the default dark background color for Sublime Text 3 under Linux)
    - Change the HEX color in line 21 to `#272822`
    - Change the HEX color in line 130 to the `#F8F8F2` (This is the default text color for Sublime Text 3 under Linux)
* Save the file and restart Sublime Text.

**Comment by upiter** [comment]
Colour values to match `Mariana` dark theme:
1. Open `outline.hidden-tmTheme`
2. Locate block with colours and replace with following values:
```xml
<key>background</key>
<string>#343D46</string>
<key>foreground</key>
<string>#D8DEE9</string>
<key>caret</key>
<string>#F9AE58</string>
<key>lineHighlight</key>
<string>#4F5B66</string>
<key>gutter</key>
<string>#343D46</string>
<key>invisibles</key>
<string>#88222233</string>
<key>selection</key>
<string>#4F5B66</string>
<key>selectionBorder</key>
<string>#222218</string>
<key>inactiveSelection</key>
<string>#4F5B66</string>
<key>shadow</key>
<string>#343D46</string>
<key>shadowWidth</key>
<string>16</string>
```

**Comment by stychos** [comment]
Tron theme:

```
<key>background</key>
<string>#14191f</string>
<key>foreground</key>
<string>#aec2e0</string>
<key>caret</key>
<string>#F8F8F0</string>
<key>lineHighlight</key>
<string>#1b232c</string>
<key>gutter</key>
<string>#14191f</string>
<key>invisibles</key>
<string>#3B3A32</string>
<key>selection</key>
<string>#183c66</string>
<key>selectionBorder</key>
<string>#082c56</string>
<key>inactiveSelection</key>
<string>#1b232c</string>
<key>shadow</key>
<string>#14191f</string>
<key>shadowWidth</key>
<string>16</string>
```
