### ISSUE TITLE
Function names are not trimmed

### ISSUE THREAD

**Issue by upiter** [warmdev/SublimeOutline#10]
## Problem
Outline panel shows function names with extra TAB symbols

## How to reproduce
1. Install [TrailingSpaces](https://github.com/SublimeText/TrailingSpaces)
2. Add TAB after any function name, before bracket:
`Initialize	(void)`
like this:
`Initialize<TAB>(void)`
3. See in `Outline` pane extra symbol after `Initialize` function name.

**Comment by warmdev** [comment]
See fix in [issue 12](https://github.com/warmdev/SublimeOutline/issues/12)
