### ISSUE TITLE
outline not functioning

### ISSUE THREAD

**Issue by Rx3210** [warmdev/SublimeOutline#11]
Why is the outline not showing?

![sketch](https://user-images.githubusercontent.com/22483897/35300409-96db7078-0088-11e8-9100-fcfafa3d083c.png)

**Comment by warmdev** [comment]
HTML files are not well supported. This is a limitation of the symbol definition for the HTML format. See https://forum.sublimetext.com/t/solved-goto-symbol-in-project-only-brings-up-css-and-not-the-html-id-attributes-etc/12403
