### ISSUE TITLE
Empty line in outline, and highlight mismatch 

### ISSUE THREAD

**Issue by Xeonilian** [warmdev/SublimeOutline#12]
Hi warmdev,
I guess, you've heard a lot. But I have to say. I am just looking for this function. Thanks a lot.
I want to use this function when I write markdown in sublime with MarkdownEditing.
Basically, it works. But I don't know why there are empty lines added between headers. And the highlight doesn't match the corresponding header. See the picture below.
![](http://images.cnblogs.com/cnblogs_com/Xeonilian/1031855/o_outline.PNG)
Do you perhaps know what do I miss or do wrong?

FYI, I find the setting file for the syntax following your instruction. It is `SymbolList - Heading.tmPreferences` for markdownEditing.
Currently, the content of file is:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Symbol List: Heading</string>
	<key>scope</key>
	<string>text.html.markdown markup.heading</string>
	<key>settings</key>
	<dict>
		<key>showInSymbolList</key>
		<integer>1</integer>
		<key>symbolTransformation</key>
		<string>
			s/\[([^]]+)\]\([^)]+\)/$1/g;
			s/\[([^]]+)\]\[[^]]+\]/$1/g;
			s/\[([^]]+)\]/$1/g;
			s/\s*#+\s*$//g;
			s/^\s*#(#*)\s*/$1/g;
			s/^#{5}/      /g;
			s/^#{4}/     /g;
			s/^#{3}/    /g;
			s/^#{2}/  /g;
			s/^#{1}//g;
			s/^(-+)\s*$/       $1/
		</string>
		<key>showInIndexedSymbolList</key>
		<integer>0</integer>
		<key>symbolIndexTransformation</key>
		<string>
			s/\s*#+\s*$//g;
		</string>
	</dict>
	<key>uuid</key>
	<string>C02A37C1-E770-472F-A13E-358FF0C6AD89</string>
</dict>
</plist>
```
Thanks a lot! 🙂

**Comment by warmdev** [comment]
Need to investigate this, but for now you can use the "Markdown GFM" syntax which seems to work well.

**Comment by warmdev** [comment]
Assuming that you have installed `PackageResourceViewer`, you can open the `outline.py` file in the `Outline` package, and add the single line marked below. This should also help solve issue https://github.com/warmdev/SublimeOutline/issues/10

```python
class OutlineRefreshCommand(TextCommand):
	def run(self, edit, symlist=None, symkeys=None, path=None, to_expand=None, toggle=None):
		self.view.erase(edit, Region(0, self.view.size()))
		symlist = [sym.strip() for sym in symlist] # Add this line
		self.view.insert(edit, 0, "\n".join(symlist))
```

**Comment by Xeonilian** [comment]
Works perfectly 👍 
Thanks！
