### ISSUE TITLE
Clicking on empty outline results in error

### ISSUE THREAD

**Issue by TonyGravagno** [warmdev/SublimeOutline#16]
Open a new file, note that the outline is empty, click it. The result is:

> IndexError: list index out of range

It needs to check if there are any symkeys before attempting to retrieve the element for [row].
Solution: In outline.py, replace current line 62 with the following block:

```
62 symkeys = sym_view.settings().get('symkeys')
63 if not symkeys:
64	return
64 region_position = symkeys[row]
```

**Comment by warmdev** [comment]
Closing as issue has been fixed by pull request
