### ISSUE TITLE
Minimap cannot be disabled

### ISSUE THREAD

**Issue by con-f-use** [warmdev/SublimeOutline#18]
I'm missing a setting to disable the minimap in just the Outline column. I'm aware, I can disable all minimaps, i.e. the one in the outline column **together with** the one in the main editing area in the menu `View` -> `Hide Minimap`.

In a picture:
![image](https://user-images.githubusercontent.com/11145016/42324704-2c0937c4-8064-11e8-806d-a0ecb6b89ff1.png)

**Comment by warmdev** [comment]
Unfortunately the minimap show/hide status is a window level setting (i.e. for the entire editor window), not a view level setting (i.e. for each tab/file), so it is not possible or easy to do this. But I would welcome any suggestions or pull request.

**Comment by warmdev** [comment]
Closing as this is not feasible to fix
