### ISSUE TITLE
Latex Outline

### ISSUE THREAD

**Issue by Crazy-Ape** [warmdev/SublimeOutline#2]
Hi, I think this plugin is a great idea, and excellent implementation! :+1: 

Could you please add support for correct latex outlines, that has sections/subsections and labels indented correctly.

**Comment by warmdev** [comment]
Content and indentation of the outline are determined by the corresponding `tmPreferences` files in the default `Latex` package. To modify these files, I recommend using the `PackageResourceViewer` package (available from Package Control). Once you have installed `PackageResourceViewer`, press `ctrl + shift + p` and then `PackageResourceViewer: Open Resource`, then navigate to or find the `LaTeX` package, then open each of the following files:

* `Symbol List - Commands.tmPreferences`
* `Symbol List - Labels.tmPreferences`
* `Symbol List - Sections.tmPreferences`

### Commands

To hide commands from `Outline`, in file `Symbol List - Commands.tmPreferences`, change the value below `showInSymbolList` from 1 to 0.

### Labels

To hide labels from `Outline`, in file `Symbol List - Labels.tmPreferences`, change the value below `showInSymbolList` from 1 to 0.

### Sections

To have proper indentation for section titles, change the `string` section below `symbolTransformation` to the content below:

```
			s/^\\part(.*)/\U($1)/g;				# Strip \part and make rest of string uppercase
			s/^\\chapter//g;					# Strip \chapter
			s/^\\section/  /g;					# Strip \section + add indent
			s/^\\subsection/    /g;				# Strip \subsection + add indent
			s/^\\subsubsection/      /g;		# Strip \subsubsection + add indent
			s/^\\paragraph/        /g;			# Strip \paragraph + add indent
			s/^\\subparagraph/          /g;		# Strip \subparagraph + add indent
			s/^(\s*)\*{0,1}\{(.*)\}\s*/$1$2/g; # Keep indent and string; strip other markup
```

After completing the above steps, you should get proper indentation in the `Outline` view.

Full credits to https://github.com/alehandrof/BetterGoTo for these modifications.

**Comment by Crazy-Ape** [comment]
Thanks! Excellent!
:-)
