### ISSUE TITLE
Useless with ES6+flow

### ISSUE THREAD

**Issue by jankuca** [warmdev/SublimeOutline#24]
I was looking for a plugin which would list the classes, methods and functions defined in a file and this looked like a feasible option. However, it does not cope well with ES6 (JavaScript) files – at least when combined with flowtype annotations.

![screen shot 2018-12-21 at 15 18 49](https://user-images.githubusercontent.com/367262/50346845-ed0c7b80-0533-11e9-9ae0-36b9e74adc74.png)

**Comment by warmdev** [comment]
Similar to https://github.com/warmdev/SublimeOutline/issues/23. If the same list is displayed when you press Ctrl + R, then not much this plugin can do.

**Comment by warmdev** [comment]
Not possible to fix due to limitation of symbol list provided by Sublime Text
