### ISSUE TITLE
in win7 x64, sublime text3 outline plugin  tab_size modification does not take effect?

### ISSUE THREAD

**Issue by juejian** [warmdev/SublimeOutline#28]
tab_size default value is **3,** when using **markdownEditing**, outline show as below:

![image](https://user-images.githubusercontent.com/12257223/68086541-28801200-fe88-11e9-87e1-75165f41a841.png)

when opening  ` Preferences -> Package Settings -> outline -> Setting - User`  to edit:

```json
{
  "tab_size": 1
}
```

save, after restart sublime text3, outline show as same as above.

I want to decrease outline content indent and remove space line,  How can I configure it?

If you have time, please reply me, thank you。

**Comment by warmdev** [comment]
For tab size issue, see https://github.com/warmdev/SublimeOutline/issues/5

For empty line issue, see https://github.com/warmdev/SublimeOutline/issues/12
