### ISSUE TITLE
Editing the Symbol List.tmPreferences file -> possible? 

### ISSUE THREAD

**Issue by ldm1417** [warmdev/SublimeOutline#29]
Hello,

Is it possible to edit the symbols list in the Outline plugin?

Is it possible to add/remove symbols? Create Symbols List for the new languages?

There is the **Symbol List.tmPreferences** file located?

Thank you!

**Comment by warmdev** [comment]
Closing as this issue duplicates https://github.com/warmdev/SublimeOutline/issues/30
