### ISSUE TITLE
Toggle sidebar not working and  "Browse Mode: Close sidebar(s)" show a blank view

### ISSUE THREAD

**Issue by gopise** [warmdev/SublimeOutline#32]
Hi,
I'm using Sublime Text Build 4077. I'm using the following command to show/hide the single outline panel on the left:
`        "command": "outline",
        "args": {
            "immediate": true,
            "other_group": "right",
            "single_pane": true,
            "project": true,
            "layout": 1
        }
`
The showing works fine but hidding by running the command again not working (nothing happen). 

Another issue is, when I use "Browse Mode: Close sidebar(s)" to close the sidebar, it will show a blank view (nothing in it) after closing and the previous view (code) will be de-focused.

I managed to look into your code and found these two might be caused by similar reason...
I've got it a quick try to fix it. 

Hope it will help:

In outline.py:
---------------------------------------------------------------------------------
class OutlineCloseSidebarCommand(WindowCommand):
    def run(self):
        prev_focus = None
        for v in self.window.views():
            if u'𝌆' in v.name():
                self.window.focus_view(v)
                self.window.run_command('close_file')
            elif v.file_name() != None: # Not console
                prev_focus = v
        if prev_focus:
            # Workaround:
            # Do this twice since ST will wrongly show a blank layout after first time even focus is correct.
            self.window.focus_view(prev_focus)
            self.window.set_layout({"cols": [0.0, 1.0], "rows": [0.0, 1.0], "cells": [[0, 0, 1, 1]]})
            self.window.focus_view(prev_focus)
            self.window.set_layout({"cols": [0.0, 1.0], "rows": [0.0, 1.0], "cells": [[0, 0, 1, 1]]})

In show.py:
---------------------------------------------------------------------------------
def show(window, view_id=None, ignore_existing=False, single_pane=False, other_group='', layout=1):
    """
    Determines the correct view to use, creating one if necessary, and prepares it.
    """
    symlist = []
    file_path = None
    prev_focus = None
    toggle = False
    if other_group:
        for v in window.views():
            if u'𝌆' in v.name():
                window.focus_view(v)
                window.run_command('close_file')
                toggle = True
            elif v.file_name() != None: # Not console
                prev_focus = v
        if toggle and prev_focus != None:
            # Workaround:
            # Do this twice since ST will wrongly show a blank layout after first time even focus is correct.
            window.focus_view(prev_focus)
            window.set_layout({"cols": [0.0, 1.0], "rows": [0.0, 1.0], "cells": [[0, 0, 1, 1]]})
            window.focus_view(prev_focus)
            window.set_layout({"cols": [0.0, 1.0], "rows": [0.0, 1.0], "cells": [[0, 0, 1, 1]]})
            return
...

**Comment by warmdev** [comment]
Blank view issue is fixed in latest commit https://github.com/warmdev/SublimeOutline/commit/19973228fc7c73da3d3172dbe86abfe8249c4c2a and will be published to Package Control soon. 

The toggle sidebar issue cannot be replicated.

**Comment by warmdev** [comment]
Blank view issue is fixed in latest release.

**Comment by Gregory-K** [comment]
@gopise little too late for a closed issue...

I wanted to toggle the side-panel with the same shortcut/hotkey, so  
https://github.com/Gregory-K/SublimeOutline  
if you want to try it
