### ISSUE TITLE
Feature development request

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [warmdev/SublimeOutline#33]
Hi Xiongbing,

Thank you for creating this plugin. I use it for my work and find it very useful.

However, I'm missing the sync feature in this plugin. When scrolling the document or jumping between markdown headings, the outline view should scroll as well, and the current heading should be highlighted.

This should be easy to add, but I'm not familiar with Python or sublime text plugin architecture.

It seems this has also been suggested in [this issue](https://github.com/warmdev/SublimeOutline/issues/3), which has been open since 2016.

I understand that you must be busy. Would you be interested in developing this, if you were compensated for your effort?

If so, can you send me your effort estimate and hourly rate at mail.ksharma.dev@gmail.com

Thanks in advance
Kshitiz

**Comment by warmdev** [comment]
Please see update on [issue 3](https://github.com/warmdev/SublimeOutline/issues/3)
