### ISSUE TITLE
doesn't jump to the line

### ISSUE THREAD

**Issue by ldm-amn** [warmdev/SublimeOutline#34]
Hi there, 

I'm using the Outline for the SystemVerilog files. 

When I click on any line in the Outline window, it doesn't jump to the relevant line in the Code Window. I used the Outline package previously and it did included this functionality. Now it stopped working...

I've tried to reinstall the Outline package - doesn't help... Close & Open the Sublime - doesn't help... So, what's the problem. 

I'm using the most updated Sublime version. What are the next steps? 

Thank you!

**Comment by warmdev** [comment]
Sorry but this issue could not be reproduced. Please try go into the packages folder (use menu `Preferences > Browse Packages`) and see if there are any leftover files from previous installations.
