### ISSUE TITLE
Default pane width

### ISSUE THREAD

**Issue by julkamny** [warmdev/SublimeOutline#38]
Hello,

I would like to know if it is possible to change the default width of the outline pane, so that whenever I open it after having closed it – with the "Browse mode: Close sidebar(s)" command –, it retains the same width. Changing the default sidebar width in the workplace file of my project (as advised here : https://stackoverflow.com/questions/17435063/how-to-set-the-width-of-the-sidebar-in-sublime-text-2) doesn't solve my problem. I'd be much grateful for your help! 

Best,
Jul

**Comment by warmdev** [comment]
Version 0.1.6 now supports changing the outline pane width via setting `outline_width`. To change the width, click "Preferences > Package Settings > Outline > Settings - User, and add the following. Default value is 0.2 which is 20% of the entire window width.

```json
{
    "outline_width": 0.2
}
```

**Comment by julkamny** [comment]
Thank you so much for adding this parameter so quickly, I'm very grateful!
