### ISSUE TITLE
Finally an outliner, a few suggestions

### ISSUE THREAD

**Issue by dracodoc** [warmdev/SublimeOutline#4]
I have been looking for this for a long time. I found your package only after I changed the search keywords from `markdown` `toc` to `outline`. 

I'll suggest to add `markdown` `toc` `table of contents` `based on titles` etc to the package description.

Other suggestions about the usage:

1. sync outline selection when cursor moved to other location
2. I didn't see the advantage of selecting the title when user clicked on a title. If I want to add some content, I first need to move the cursor otherwise my input will replace title. If I want to edit title, I still need to move the selection unless I want to rewrite the line from scratch.
I think a better way is to position the cursor after the title, but with no text selected. If user have `highlight current line` on, it's still easy to see where is the cursor.
3. there is a minimap in the outline since I have minimap in my file. Can it be turned off?
4. Selecting the title doesn't have much use to me, but selecting the whole range of a title, including the title and content can be useful. Outliner often support drag and drop to reorganize the titles. If drag and drop reorganizing is too complex, at least we can double click title to select title and content, then cut and paste to new location.
5. A minor issue is there is a square before the `outline` title of the side window. This is could be related to my Chinese windows.
![2016-11-21_140710](https://cloud.githubusercontent.com/assets/1730496/20496630/ff9a5d36-aff3-11e6-996b-abf027de059f.png)

**Comment by warmdev** [comment]
Thank you for your feedback! 

1. This is related to https://github.com/warmdev/SublimeOutline/issues/3. I already have some ideas, and will implement this when I get time.
2. The purpose was to highlight the line, but I'll look into the "highlight current line" function and use that instead.
3. minimap is a global setting that applies to the entire window, and cannot be turned of for an individual view from API.
4. This is a great feature to have, and I'll look into that.
5. This is a Windows issue, as the character used there is not in the default font on Windows.

**Comment by dracodoc** [comment]
Thanks for the quick response!

"highlight current line" can be turned on in Preference -> settings. Add `"highlight_line": true,` to user settings. The color of highlight can be adjusted from the theme.

Can we add a command to turn on/off outline? Right now I have to use layout -> single column to turn it off. With a command, we can access from ctrl-shift-p, and we can also assign keyboard shortcut to it.

**Comment by warmdev** [comment]
Yes there is a command "Browse mode: Close sidebar(s)".

**Comment by dracodoc** [comment]
Maybe the command can be renamed to "close outline" ? Then it will appear in the list when user input "outline". And technically this is not a sidebar.

**Comment by warmdev** [comment]
Thanks! I'll add this. Some code change is needed, as currently the close command will close both `Outline` and also `FileBrowser` if they are used together.

**Comment by tol182** [comment]
does it support markup languages (XML, YAML)?

**Comment by warmdev** [comment]
Sorry it does not support XML or YAML.

**Comment by jbiskofski** [comment]
Man, thank you so much for making this. This has been missing from Sublime forever. I've seen a lot of posts on a lot of forums of people asking for this. Maybe you can change the description of the package to include the word "Symbols", something like "Symbols pane" "Symbols list" - I feel like this feature is usually related to the word symbol.

Anyhow, I think the two main upgrades your package needs are 

1 - A way to order the outline in alphabetical order. This is a feature the symbols view in komodo,eclipe and atom has.

2 - It should just use the theme/color-scheme of the editor. Maybe just use whatever the file browser is set to use. I feel that would be cleaner than having its own theme.

Thanks again for the great work.

**Comment by jamesrbrindle** [comment]
I would like to +1 @jbiskofski suggestion #1 and say that alphabetic sort on a large file is a must.

**Comment by earcanal** [comment]
+1 for @dracodoc item 4.  This plugin is great for _visualising_ structure, but it would be even better if you could _alter_ it at the "chunk level".

**Comment by tmc9031** [comment]
@warmdev how about `1. sync outline selection when cursor moved to other location`
i also need this feature significantly for edit markdown text, then i can know which section i am editing
thanks outline plugin

**Comment by dabro666** [comment]
Hi @tmc9031 

I've create pull request #21 for this feature.
Outline selection syncronized when changes have been made to a view.

**Comment by dabro666** [comment]
@warmdev 
You can also replace "on_modified" with "on_deactivated".
In that way, outline selection will be updated as soon as user click on Symbol in Outline Tab.

On the one side this is better for performance.
But on the other, if user add new Symbols in current View, they are not added into Outline View Tab until  current view loses input focus. 

At my side file editing with 18k lines and 400 Symbols works great with "on_modified".
So, I recommend using my original PR.

**Comment by warmdev** [comment]
Release 0.1.4 should address the syncing issue (outline pane will now scroll to current symbol location on save) and the highlighting issue (added options to highlight entire block of text/code under the current symbol, or to highlight the symbol title only (previous implementation), or to have no highlight (simply put the cursor at the end of the symbol line).

**Comment by warmdev** [comment]
Release 0.1.5 addresses the color scheme issue (options to inherit editor color scheme or use own scheme). Closing this issue.
