### ISSUE TITLE
Change indent width

### ISSUE THREAD

**Issue by certainlyakey** [warmdev/SublimeOutline#5]
Thanks for a great plugin – writing my thesis now with it constantly open. 

One quick question — is it possible to change the indent width for headings in the outline? I tried to set `tab_size` to a higher value, but it doesn't seem to do anything.

**Comment by warmdev** [comment]
Indent width is defined in the `tmPreferences` file corresponding to the file syntax. If you are using LaTeX, see https://github.com/warmdev/SublimeOutline/issues/2 for how to modify the `Symbol List - Sections.tmPreferences` file.

**Comment by certainlyakey** [comment]
I'm using Markdown. Does it mean that the indenting will be changed globally for this syntax, not just for the Outline window?

**Comment by warmdev** [comment]
The indenting should only influence what's displayed in this plugin as well as the symbol list (Ctrl + R/CMD + R). It does not influence the indenting inside your actual markdown file.
