### ISSUE TITLE
Can you order alphabetically the list?

### ISSUE THREAD

**Issue by lmajano** [warmdev/SublimeOutline#6]
Can you order alphabetically the list?

**Comment by warmdev** [comment]
I think it is possible by modifying the source file `outline.py` line 22 (change to `self.view.insert(edit, 0, "\n".join(symlist.sort()))`. You can use `PackageResourceViewer` to do this. See https://github.com/warmdev/SublimeOutline/issues/2 for instructions on using `PackageResourceViewer`.

**Comment by WallStProg** [comment]
Tried that, and it doesn't seem to work.  I get an empty outline when I add `.sort()`.  Removing that fixes the display, but of course it's not sorted.

I'm totally ignorant re: python so sure I'm missing something obvious.  Any help would be appreciated.

And, many thanks for this excellent addition to Sublime!  This was the last bit holding me back from switching over to it

**Comment by dabro666** [comment]
Hi @WallStProg 
Is it still actual?

I found the solution, but it's work not good with parents.
I can spend more time later to solve this problem, but now all "symbols" are sorted in alphabetical order, so you lose parent dependences. For example functions in classes in edited oytline.py:
![outline_alphabetical](https://user-images.githubusercontent.com/31410405/39181907-c95b9d0c-47c3-11e8-9cd3-a866218630a3.png)

# SOLUTION:
In file `outline.py` replace lines 74 and 97:
```python
symlist = view.get_symbols()
```
with:
```python
symlist = sorted(view.get_symbols(), key=lambda tup: tup[1].lstrip())
```

If you want to add switch to outline-settings, you need to replace lines 74 and 97 with:
```python
if sym_view.settings().get('outline_alphabetical'):
    symlist = sorted(view.get_symbols(), key=lambda tup: tup[1].lstrip())
else:
    symlist = view.get_symbols()
```
and add to `outline.sublime-settings` file next lines:
```json
// true: Enable alphabetical sort in output.
// false: default because of loosing parent dependences.
"outline_alphabetical": false,
```
then, by modifying this setting in user settings, you can easily switch between alphabetical and original order.

**Comment by WallStProg** [comment]
Thanks for the suggestion!  But unfortunately, no joy :-(

Perhaps this has something to do with the fact that most of my work is in C/C++, but when I made those changes to the script, it appears that the Outliner plugin was somehow disabled.  

I had to delete and reinstall in order to get it back.

Not sure how to troubleshoot a plugin, let me know if you have any suggestions and I'll try again.

**Comment by TonyGravagno** [comment]
I request that this issue be re-opened so that #14 can be considered for merge as a solution to this issue/request/inquiry.
For anyone that did not have success with #13, please try this 2-line enhancement plus the setting.

**Comment by dabro666** [comment]
@TonyGravagno thanks for your solutions. It looks much more neatly.
I have no time to understand the structures in ST and Outline, it was my first experience.

**Comment by warmdev** [comment]
Many thanks @TonyGravagno and @dabro666 for the contributions. I've also added a command to toggle the sorting. Please try out the new release.

**Comment by TonyGravagno** [comment]
v0.1.2 verified with manual install.

Added this to keymap to quickly toggle sorting:
`{ "keys": ["ctrl+shift+o"], "command": "outline_toggle_sort" },`

I recommend a small update on the README.

This is really great. 谢谢!

**Comment by WallStProg** [comment]
> Well, I'm sorry to hear that, @WallStProg

Finally got around to giving this another try, and I was able to get it working.  For me at least, it required first removing the original package installed via Package Control, and then doing a manual installation:

```
cd "/Users/btorpey/Library/Application Support/Sublime Text 3/Packages"
git clone https://github.com/warmdev/SublimeOutline.git Outline
```

Thanks very much for this -- very handy!
