### ISSUE TITLE
Outline creates extra column after closing and (re)opening ST3

### ISSUE THREAD

**Issue by SupportBod** [warmdev/SublimeOutline#8]
Already pointed out as Known Issue:  
package may not work if you use a multi-column/row layout

ST3 - Build 3143.

What if Outline creates the extra column on (re)opening ST3?

I have been using Outline for some days now and when it is active, i t works great for most files.  
But, when i'm done editing and close ST3, on reopening ST3 i have a 2 column layout and Outline is not active. Because i have the second column active, outine will not be activated.

To reactivate Outline i must go back to 1 column and reactivate Outline with ctrl+shift+P > browse mode.

Do you (or someone who is reading this) know a faster method to reactivate Outline or keep it active on reopening ST3?

**Comment by SupportBod** [comment]
Got it running again with extra row activated.
But still have to manually reactivate outline.

Also getting a traceback after activating outline and selecting the empty list:
```python
Traceback (most recent call last):
  File "D:\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\Sublime Text 3\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "outline in D:\Sublime Text 3\Data\Installed Packages\Outline.sublime-package", line 49, in on_selection_modified
IndexError: list index out of range
```
Please advice on how to keep outline active on (re)opening ST3 and what can i do about the traceback above.
After switching between tabs outline will load the list without error.

If there are questions, please let me know.

**Comment by warmdev** [comment]
Sorry for late reply. Please confirm if the following is correct. I never had any issue with Outline not being loaded/activated on startup.
1. There are only two columns and one of them is Outline, 
2. Close ST3, and open again, and Outline is not activated. Where Outline should be is empty.

Regarding the traceback, as the list is empty, clicking the list would cause a reference to a list item that does not exist. It's not a serious issue, although I should probably add a range check.

**Comment by warmdev** [comment]
Closing as could not replicate the bug
