### ISSUE TITLE
suggestion: add comments

### ISSUE THREAD

**Issue by migliori** [warmdev/SublimeOutline#9]
Hi,

Thanks for this very useful plugin.

I use it on large php class files for example: it would be great if we could view some comments in the output panel, or separate functions by group in any way.

**Comment by warmdev** [comment]
Sorry for late reply. 

To put comments in the Outline panel, you need to add a regex filter to the corresponding `Symbol List.tmPreferences` file for PHP to extract the comments (see https://github.com/warmdev/SublimeOutline/issues/2 for how to work with the file). If there are a large amount of comments, this might make the Outline pane very cluttered.

Note that Outline simply displays the symbol list as defined in the file mentioned above in the order they appear in the file. Grouping may not be feasible.

**Comment by warmdev** [comment]
No easy fix due to limitation of symbol list.
